# Generated by Django 5.2.6 on 2025-09-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='Sectionname',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='name',
            new_name='standardname',
        ),
    ]
